contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #ampliseq channel"
    url: https://nfcore.slack.com/channels/ampliseq
    about: Discussion about the nf-core/ampliseq pipeline
